CREATE TABLE IF NOT EXISTS people (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  inserted_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  first_name text NOT NULL,
  last_name text NOT NULL,
  avatar text NOT NULL,
  birthday DATE NULL,
  biography text NOT NULL,
  city text NOT NULL,
  work text NOT NULL
);